name: Publish to WinGet
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: Fndroid.ClashForWindows
          token: ${{ secrets.WINGET_TOKEN }}
